ALTER TABLE `b_basic_data`
    ADD COLUMN `wind_power_resource`                  varchar(255)   NULL DEFAULT NULL COMMENT '已规划风力发电资源（GW）' AFTER `id`,
    ADD COLUMN `photovoltaic_resource`                varchar(255)   NULL DEFAULT NULL COMMENT '已规划光伏发电资源(GW)' AFTER `wind_power_resource`,
    ADD COLUMN `grid_energy_price`                    decimal(19, 6) NULL DEFAULT NULL COMMENT '新能源并网电价(￥/kWh)' AFTER `photovoltaic_resource`,
    ADD COLUMN `storage_standards_proportion`         double         NULL DEFAULT NULL COMMENT '新能源配套储能标准装机量比例(%)' AFTER `grid_energy_price`,
    ADD COLUMN `energy_discarded`                     double         NULL DEFAULT NULL COMMENT '风力及光伏发电弃电量(kWh)' AFTER `storage_standards_proportion`,
    ADD COLUMN `energy_grid_electricity_proportion`   double         NULL DEFAULT NULL COMMENT '内蒙专有：新能源可并网电量比例(%)' AFTER `energy_discarded`,
    ADD COLUMN `wind_operation_hours`                 double         NULL DEFAULT NULL COMMENT '风力等效发电时长(h/年)' AFTER `energy_grid_electricity_proportion`,
    ADD COLUMN `pv_operation_hours`                   double         NULL DEFAULT NULL COMMENT '光伏等效发电时长（h/年）' AFTER `wind_operation_hours`,
    ADD COLUMN `energy_storage_standard_hours`        double         NULL DEFAULT NULL COMMENT '新能源配套储能标准时长（h）' AFTER `pv_operation_hours`,
    ADD COLUMN `htdrogen_electricity_proportion`      double         NULL DEFAULT NULL COMMENT '制氢可下电量比例（%）' AFTER `energy_storage_standard_hours`,
    ADD COLUMN `heat_temperature`                     double         NULL DEFAULT NULL COMMENT '供暖温度(℃)' AFTER `htdrogen_electricity_proportion`,
    ADD COLUMN `civil_heat_prices`                    decimal(19, 6) NULL DEFAULT NULL COMMENT '民用供暖价格（￥/㎡/月）' AFTER `heat_temperature`,
    ADD COLUMN `industry_heat_prices`                 decimal(19, 6) NULL DEFAULT NULL COMMENT '工商业供暖价格（￥/㎡/月）' AFTER `civil_heat_prices`,
    ADD COLUMN `heat_duration_hours`                  int            NULL DEFAULT NULL COMMENT '年供暖时长（天）' AFTER `industry_heat_prices`,
    ADD COLUMN `civil_heat_area`                      double         NULL DEFAULT NULL COMMENT '民用供暖面积(㎡)' AFTER `heat_duration_hours`,
    ADD COLUMN `industry_heat_area`                   double         NULL DEFAULT NULL COMMENT '工商业用供暖面积(㎡)' AFTER `civil_heat_area`,
    ADD COLUMN `green_oxygen_price`                   decimal(19, 6) NULL DEFAULT NULL COMMENT '绿氢卖出（￥/t）' AFTER `industry_heat_area`,
    ADD COLUMN `energy_storage_station_grid_distance` double         NULL DEFAULT NULL COMMENT '储能电站与电网接入变电站距离（公里）' AFTER `green_oxygen_price`,
    ADD COLUMN `power_grid_price`                     decimal(19, 6) NULL DEFAULT NULL COMMENT '接入电网缆线成本（￥/公里）' AFTER `energy_storage_station_grid_distance`,
    ADD COLUMN `energy_power_energy_sorage_distance`  double         NULL DEFAULT NULL COMMENT '新能源电站与储能电站距离（公里）' AFTER `power_grid_price`,
    ADD COLUMN `energy_storge_land_price`             decimal(19, 6) NULL DEFAULT NULL COMMENT '储能电站用地价格（￥/亩）' AFTER `energy_power_energy_sorage_distance`,
    ADD COLUMN `rent_energy_land_price`               decimal(19, 6) NULL DEFAULT NULL COMMENT '新能源用地租金成本（￥/亩）' AFTER `energy_storge_land_price`,
    ADD COLUMN `social_average_salary`                decimal(19, 6) NULL DEFAULT NULL COMMENT '社平工资（￥）' AFTER `rent_energy_land_price`,
    ADD COLUMN `social_security_expenses`             decimal(19, 6) NULL DEFAULT NULL COMMENT '社保相关费用（￥）' AFTER `social_average_salary`,
    ADD COLUMN `long_loan_rate`                       double         NULL DEFAULT NULL COMMENT '长期贷款利率（%）' AFTER `social_security_expenses`,
    ADD COLUMN `long_loan_grace_period`               int            NULL DEFAULT NULL COMMENT '长期贷款宽限期(年)' AFTER `long_loan_rate`,
    ADD COLUMN `long_loan_year`                       int            NULL DEFAULT NULL COMMENT '长期贷款年限(年)' AFTER `long_loan_grace_period`,
    ADD COLUMN `short_loan_rate`                      double         NULL DEFAULT NULL COMMENT '短期贷款利率（%）' AFTER `long_loan_year`,
    ADD COLUMN `short_loan_year`                      int            NULL DEFAULT NULL COMMENT '短期贷款年限(年)' AFTER `short_loan_rate`,
    DROP COLUMN `installed_capacity`,
    DROP COLUMN `heating_price`,
    DROP COLUMN `total_heating`,
    DROP COLUMN `loan_rate`,
    DROP COLUMN `loan_years`;
